/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as NeetRouteImport } from './routes/neet'
import { Route as JeeRouteImport } from './routes/jee'
import { Route as FindAMentorRouteImport } from './routes/find-a-mentor'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BecomeAMentorRouteImport } from './routes/become-a-mentor'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ResourcesSlugRouteImport } from './routes/resources.$slug'
import { Route as AdminResourcesRouteImport } from './routes/admin.resources'
import { Route as AdminMentorsRouteImport } from './routes/admin.mentors'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminContactsRouteImport } from './routes/admin.contacts'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const NeetRoute = NeetRouteImport.update({
  id: '/neet',
  path: '/neet',
  getParentRoute: () => rootRouteImport,
} as any)
const JeeRoute = JeeRouteImport.update({
  id: '/jee',
  path: '/jee',
  getParentRoute: () => rootRouteImport,
} as any)
const FindAMentorRoute = FindAMentorRouteImport.update({
  id: '/find-a-mentor',
  path: '/find-a-mentor',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeAMentorRoute = BecomeAMentorRouteImport.update({
  id: '/become-a-mentor',
  path: '/become-a-mentor',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesSlugRoute = ResourcesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ResourcesRoute,
} as any)
const AdminResourcesRoute = AdminResourcesRouteImport.update({
  id: '/admin/resources',
  path: '/admin/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMentorsRoute = AdminMentorsRouteImport.update({
  id: '/admin/mentors',
  path: '/admin/mentors',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/admin/leads',
  path: '/admin/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContactsRoute = AdminContactsRouteImport.update({
  id: '/admin/contacts',
  path: '/admin/contacts',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/become-a-mentor': typeof BecomeAMentorRoute
  '/contact': typeof ContactRoute
  '/find-a-mentor': typeof FindAMentorRoute
  '/jee': typeof JeeRoute
  '/neet': typeof NeetRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/mentors': typeof AdminMentorsRoute
  '/admin/resources': typeof AdminResourcesRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/become-a-mentor': typeof BecomeAMentorRoute
  '/contact': typeof ContactRoute
  '/find-a-mentor': typeof FindAMentorRoute
  '/jee': typeof JeeRoute
  '/neet': typeof NeetRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/mentors': typeof AdminMentorsRoute
  '/admin/resources': typeof AdminResourcesRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/become-a-mentor': typeof BecomeAMentorRoute
  '/contact': typeof ContactRoute
  '/find-a-mentor': typeof FindAMentorRoute
  '/jee': typeof JeeRoute
  '/neet': typeof NeetRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/mentors': typeof AdminMentorsRoute
  '/admin/resources': typeof AdminResourcesRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/become-a-mentor'
    | '/contact'
    | '/find-a-mentor'
    | '/jee'
    | '/neet'
    | '/resources'
    | '/sitemap.xml'
    | '/admin/contacts'
    | '/admin/dashboard'
    | '/admin/leads'
    | '/admin/login'
    | '/admin/mentors'
    | '/admin/resources'
    | '/resources/$slug'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/become-a-mentor'
    | '/contact'
    | '/find-a-mentor'
    | '/jee'
    | '/neet'
    | '/resources'
    | '/sitemap.xml'
    | '/admin/contacts'
    | '/admin/dashboard'
    | '/admin/leads'
    | '/admin/login'
    | '/admin/mentors'
    | '/admin/resources'
    | '/resources/$slug'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/become-a-mentor'
    | '/contact'
    | '/find-a-mentor'
    | '/jee'
    | '/neet'
    | '/resources'
    | '/sitemap.xml'
    | '/admin/contacts'
    | '/admin/dashboard'
    | '/admin/leads'
    | '/admin/login'
    | '/admin/mentors'
    | '/admin/resources'
    | '/resources/$slug'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BecomeAMentorRoute: typeof BecomeAMentorRoute
  ContactRoute: typeof ContactRoute
  FindAMentorRoute: typeof FindAMentorRoute
  JeeRoute: typeof JeeRoute
  NeetRoute: typeof NeetRoute
  ResourcesRoute: typeof ResourcesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminContactsRoute: typeof AdminContactsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMentorsRoute: typeof AdminMentorsRoute
  AdminResourcesRoute: typeof AdminResourcesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/neet': {
      id: '/neet'
      path: '/neet'
      fullPath: '/neet'
      preLoaderRoute: typeof NeetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jee': {
      id: '/jee'
      path: '/jee'
      fullPath: '/jee'
      preLoaderRoute: typeof JeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-a-mentor': {
      id: '/find-a-mentor'
      path: '/find-a-mentor'
      fullPath: '/find-a-mentor'
      preLoaderRoute: typeof FindAMentorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-a-mentor': {
      id: '/become-a-mentor'
      path: '/become-a-mentor'
      fullPath: '/become-a-mentor'
      preLoaderRoute: typeof BecomeAMentorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/$slug': {
      id: '/resources/$slug'
      path: '/$slug'
      fullPath: '/resources/$slug'
      preLoaderRoute: typeof ResourcesSlugRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/admin/resources': {
      id: '/admin/resources'
      path: '/admin/resources'
      fullPath: '/admin/resources'
      preLoaderRoute: typeof AdminResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/mentors': {
      id: '/admin/mentors'
      path: '/admin/mentors'
      fullPath: '/admin/mentors'
      preLoaderRoute: typeof AdminMentorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/admin/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/contacts': {
      id: '/admin/contacts'
      path: '/admin/contacts'
      fullPath: '/admin/contacts'
      preLoaderRoute: typeof AdminContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ResourcesRouteChildren {
  ResourcesSlugRoute: typeof ResourcesSlugRoute
}

const ResourcesRouteChildren: ResourcesRouteChildren = {
  ResourcesSlugRoute: ResourcesSlugRoute,
}

const ResourcesRouteWithChildren = ResourcesRoute._addFileChildren(
  ResourcesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BecomeAMentorRoute: BecomeAMentorRoute,
  ContactRoute: ContactRoute,
  FindAMentorRoute: FindAMentorRoute,
  JeeRoute: JeeRoute,
  NeetRoute: NeetRoute,
  ResourcesRoute: ResourcesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminContactsRoute: AdminContactsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMentorsRoute: AdminMentorsRoute,
  AdminResourcesRoute: AdminResourcesRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
